### ISSUE TITLE
Pandora Port

### ISSUE THREAD

**Issue by Zero3K** [funfun-dc5/qtbrynhildr#1]
It would be nice if someone could get it working on the Pandora (http://openpandora.org). A guy on its forums has gotten QTBrynhildr to compile for it but it runs slowly and without any audio being outputted.

**Comment by funfun-dc5** [comment]
It may be hard for Pandora to run Qt Brynhidlr. I think it's need to optimize for low spec. platform.

**Comment by Zero3K** [comment]
Can you please try working on that?

**Comment by Zero3K** [comment]
I have got a guy working on porting it to there. There are a few issues with it though:
1. The sound is not working because of buffer underruns, etc.
2. The framerate is low when connected to a PC via my Home's Wireless Network.
3. It is hawving trouble staying connected when using the wireless network I mentioned.

**Comment by Zero3K** [comment]
All the issues are because of me using the Pandora's internal wifi instead of a usb stick. Anyways, he has publicly released it. Its page can be found at http://repo.openpandora.org/?page=detail&app=qtbrynhildr_ptitseb and the forum post regarding it can be found at https://www.pyra-handheld.com/boards/threads/qtbrynhildr.77392/. You can mention those links on your blog if you want to do so.
