### ISSUE TITLE
Buffer Underruns with Sound enabled

### ISSUE THREAD

**Issue by Zero3K** [funfun-dc5/qtbrynhildr#13]
There are a lot of them that are occurring when running it on the Pandora. Please see if you can fix it.

**Comment by Zero3K** [comment]
Turns out that its using too much CPU which is causing the underruns.

**Comment by Zero3K** [comment]
According to the hw_params file at /proc/asound/card0/pcm0p/sub0, the buffer_size is fixed at 4800 and the period_size is fixed at 960 no matter what the .asoundrc has set in it.

**Comment by Zero3K** [comment]
Its an issue with the program, not with the OS acccording to one of the developers of Pandora's OS.

**Comment by Zero3K** [comment]
So, can anything be done to fix it or not?

**Comment by funfun-dc5** [comment]
I set the write buffer size for sound device.

QAudioOutput->setBufferSize(48000)
