### ISSUE TITLE
Coverity Scan

### ISSUE THREAD

**Issue by Zero3K** [funfun-dc5/qtbrynhildr#14]
Maybe you could try running it through that service (which you can find by going to https://scan.coverity.com/).

**Comment by funfun-dc5** [comment]
Thanks for your information. I registered this project.

**Comment by Zero3K** [comment]
I was the one who registered it and added you to it. Did you upload a build of it so it can be analyzed? You can download the build tool at https://scan.coverity.com/download?tab=cxx and upload it by going to https://scan.coverity.com/projects/qtbrynhildr/builds/new.

**Comment by Zero3K** [comment]
You can download the build tool at https://scan.coverity.com/download?tab=cxx and upload it by going to https://scan.coverity.com/projects/qtbrynhildr/builds/new.

**Comment by funfun-dc5** [comment]
I added "Qt Brynhildr" and received first results at this morning.

**Comment by Zero3K** [comment]
I see the results also and am happy to see that more issues were found and fixed :) .

**Comment by Zero3K** [comment]
Will you be releasing a new version soon that fixes those defects that it reported?

**Comment by funfun-dc5** [comment]
I'm checking it's report now. I will release a new version including bug fixes and a new feature within 2 weeks.

**Comment by Zero3K** [comment]
2 Weeks? Well, you could just update its source code with the fixes so the guy doing the Pandora port will be able to make a new build of it. Anyways, what is the new feature that you're planning on adding?

**Comment by Zero3K** [comment]
Thanks for using it to improve QtBrynhildr. I'm marking this as closed since its no longer an issue.

**Comment by Zero3K** [comment]
You should be submitting a build of it to Coverity Scan when releasing a new version of it.

**Comment by Zero3K** [comment]
The latest version hasn't been scanned for defects via it yet.

**Comment by Zero3K** [comment]
I am closing it since the new version was scanned. I expect its service to be used on occasion to help fix QtBrynhildr.
