### ISSUE TITLE
Issue with showing certain programs

### ISSUE THREAD

**Issue by Zero3K** [funfun-dc5/qtbrynhildr#16]
Programs that use DirectX components (Such as direct2d) don't show up when they are in their own Full Screen mode.

**Comment by funfun-dc5** [comment]
I reported this Issue to IchiGeki-san (developer of Brynhildr) by E-mail. He said it was a restriction of Brynhildr.

**Comment by Zero3K** [comment]
Can it be fixed?

**Comment by Zero3K** [comment]
I'm closing this since its an issue with Brynhildr, not QtBrynhildr.
