### ISSUE TITLE
Unnecessary Dialog Box

### ISSUE THREAD

**Issue by Zero3K** [funfun-dc5/qtbrynhildr#28]
I think that the "[QtBrynhildr] Please check server sound device!" dialog box should be removed or fix the issue that is causing it to show up.

**Comment by Zero3K** [comment]
Actualy, I think that there should be an option to disable the showing of the error boxes.

**Comment by Zero3K** [comment]
I hope to see that option in a later version.

**Comment by funfun-dc5** [comment]
I implemented in v232-rc1.
