### ISSUE TITLE
Suggestion regarding its Full Screen mode

### ISSUE THREAD

**Issue by Zero3K** [funfun-dc5/qtbrynhildr#6]
When using it, the Title and Status Bars should be hidden until the user hovers near the top/bottom of the screen.

**Comment by Zero3K** [comment]
The full screen option is almost perfect. Now the only things I would like to be hidden are the grey bars that are showing when in Full Screen mode.

**Comment by Zero3K** [comment]
The Menu and Status Bars aren't showing automatically when exiting out of Full Screen Mode in the latest version.

**Comment by funfun-dc5** [comment]
I fixed it and released v1.5.1.

**Comment by Zero3K** [comment]
Thanks for doing that. I'm closing this now since it has been fixed.
